#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <skeleton_icons.h>

int32_t skeleton_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm skeleton!");

    return 0;
}
